### ISSUE TITLE
307 error downloading Files as non-owner

### ISSUE THREAD

**Issue by mdecerbo** [IgnoredAmbience/yahoo-group-archiver#101]
As a non-owner, I am trying to back up the group https://groups.yahoo.com/neo/groups/solzhenitsyn-l/

I backed up the messages okay, but not the files.
I can see that the group has files when logged into Yahoo as a member, but I get:

```
$ python ./yahoo.py -v -f -ct T-cookie.txt -cy Y-cookie.txt solzhenitsyn-l
2019-11-07 11:58:14.043 EST INFO requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): groups.yahoo.com
2019-11-07 11:58:14.119 EST DEBUG requests.packages.urllib3.connectionpool "GET /api/v2/groups/solzhenitsyn-l/files HTTP/1.1" 307 None
2019-11-07 11:58:14.120 EST ERROR archive_files Couldn't access Files functionality for this group
```
I have logged out of Yahoo, logged back in and updated the T and Y cookie files, but get the same problem. Please let me know how I can help debug this. Thanks!

**Comment by d235j** [comment]
@mdecerbo The group solzhenitsyn-l returns an Error 404 Not Found for me. Is it a secret group?

`-ct` and `-cy` don't take files — they take cookie data directly. You want to pass

`-ct 'z=longstringhere' -cy 'v=longstringhere'`.

**Comment by mdecerbo** [comment]
I didn't think the group was secret! Here's the link: https://groups.yahoo.com/neo/groups/solzhenitsyn-l/info

But thanks very much for clearing up my confusion about how to pass the cookies! So of course:
```
$ python ./yahoo.py -w -v -f -ct `cat T-cookie.txt` -cy `cat Y-cookie.txt` solzhenitsyn-l
```
worked just fine.
