### ISSUE TITLE
My browser session's T and Y  cookie have a different structure/seem to be invalid

### ISSUE THREAD

**Issue by SanneSideUp** [IgnoredAmbience/yahoo-group-archiver#106]
First, thanks for creating the script, I have some 100 groups I would need to archive for the OTW until the deadline and I have a basic understanding of commandlines, so I thought I give this a try.

Not sure what I'm doing wrong, though. I looked up my browser session's Y and T cookie. Manual says "The cookies should look like this, where someLongText and someShortText are arbitrary strings:"

For example, my Y cookie start with a '=', not with a 'v=' and instead of &1= after the first long text mine has a &iz=

The only other cookie that starts with a v= is the AS one, but this one seem too short, it basically only, "v=1&s=someLongText"
Subsequently, the script doesn't know what to with the "iz", "r" and "intl" commands it gets from my Y cookie and I get a "yahoo.py: error too few arguments" error. 

Also, there is no E cookie in my browser session, despite me being in the EU (might be not an issue, though)...

I'm grateful for any help.

**Comment by Pablo2m** [comment]
Could you tell us what browser you are using?

**Comment by SanneSideUp** [comment]
Chrome Version 78.0.3904.87 (official  Build) (64-Bit) on Windows 10 Build 1903

**Comment by ugcheleuce** [comment]
Yes, different browsers or extensions export the cookies in different formats.  I have not been able to get the scripts to work with a cookie.txt file at all, so I have to specify the T and Y cookies specifically.

- If you have Vivaldi, this extension gets you the cookies in the correct format:
http://www.editthiscookie.com/
- I have been unable to find an extension for Firefox that outputs the cookies in the correct style.
- In Chrome, clicking the lock symbol in the address field works, but you have to double-click the value before copying it, to make sure you select the entire value and not just the visible portion of it.

**Comment by SanneSideUp** [comment]
In Chrome I managed to find Cookie values for Y and T that look more like the ones in manual via the Dev Tools (F12) (and then via Application->Cookies. Still no E cookies, though.
Script throws a lot of UnicodeDecodeError "' but seems to now at least do something (and according to this [Issue here](https://github.com/IgnoredAmbience/yahoo-group-archiver/issues/88) I just need to upgrade by Python version to 3 to fix that) :-)

**Comment by IgnoredAmbience** [comment]
In chrome the window noted in the readme file doesn't make it clear that there's more text in the textbox than is shown on the screen, using the cursor or double click to select everything should get the correct cookie values.
I should update the readme to make this clear...
