### ISSUE TITLE
Installation Error: Could not open requirements file [Errno 2]

### ISSUE THREAD

**Issue by zenmindai** [IgnoredAmbience/yahoo-group-archiver#128]
I guess I'm still a Pythong noob, because I need help with an error. I'm attempting to install the Archiver on Ubuntu 19.10 on both Python 2.7 and Python 3 but I'm getting following error: 

Could not open requirements file: [Errno 2] No such file or directory: 't'

I've done some troubleshooting with lots of variation. I've tried adding './' to './requirements.txt' and made sure to run the commands as sudo. However, I'm getting the same error. 

What am I missing?

**Comment by Pablo2m** [comment]
Try to run: 
pip install requests
pip install warcio

**Comment by zenmindai** [comment]
That did it! I was able to install and run the files.

However, I'm running into an authentication error, but I'll search and post on that separately.
