### ISSUE TITLE
Error on downloading files or photos

### ISSUE THREAD

**Issue by n4mwd** [IgnoredAmbience/yahoo-group-archiver#14]
The login is for the group owner and does have FILE read permission.  It complains about not having FILE read permission even if I use the -i option to only download photos.

"httpStatus":307,"errorMessage":"User does not have READ permission for FILE. Messa...","errorCode":1101,"sid":"SID:YHOO:groups.yahoo.com:3d12028a8c0cbfd5551797b36bc0995a:0"}}
Traceback (most recent call last):
  File "./yahoo.py", line 195, in <module>
    archive_files(yga)
  File "./yahoo.py", line 75, in archive_files
    file_json = yga.files()
  File "/home/xxxxx/yahoo-group-archiver/yahoogroupsapi.py", line 82, in get_json
    raise e
requests.exceptions.HTTPError

**Comment by IgnoredAmbience** [comment]
Hmm, unusual. The stack trace you've given is for a case where it was trying to download files, line 75.

Is this still occurring with the latest version of the program? (There's been quite a lot of changes made in the last few days)

**Comment by n4mwd** [comment]
Not getting this same error with the latest version.
