### ISSUE TITLE
Bad messages with 1001 error stop export

### ISSUE THREAD

**Issue by jrbray1** [IgnoredAmbience/yahoo-group-archiver#18]
I can run through 700 odd messages of the 2000 in my archive, then I get

Exception raised on uri: http://groups.yahoo.com/api/v1/groups/REDACTED/messages/1470/raw
...
"ygError":{"hostname":"gapi2.grp.bf1.yahoo.com","httpStatus":500,"errorMessage":"Internal error: Error during message fetch","errorCode":1001,"sid":"SID:YHOO:groups.yahoo.com:REDACTEDD:0"}}
Traceback (most recent call last):
  File "./yahoo.py", line 194, in <module>
    archive_email(yga, reattach=(not args.no_reattach), save=(not args.no_save))
  File "./yahoo.py", line 38, in archive_email
    raw_json = yga.messages(id, 'raw')
  File "/home/john/yahoo-group-archiver.git/trunk/yahoogroupsapi.py", line 84, in get_json
    raise e
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://groups.yahoo.com/api/v1/groups/REDACTED/messages/1470/raw

Manual requesting the URL suggests a scattering of bad messages from then on. I'd be happy to sacrifice the bad messages if there were a workaround to skip over them without me hard-coding the numbers in the script.

**Comment by cas206** [comment]
https://github.com/IgnoredAmbience/yahoo-group-archiver/pull/16/files/165fdd1f91cdf62e1e496e55e32fd31fc4586fe2..f9413cbc4eeff3610e5f4a88ae6e6d5ba9645143

c33howard has a resume and skip option.  However, it still requires you to manually add the bad message number to a list on the command line and restart.  Although resume option looks to speed up the restart.

**Comment by jrbray1** [comment]
Thanks, after a patch of 20 bad messages in 100 where I was losing the will to live, it perked up and I've got the rest. Note for others, I needed


    BASE_URI="http://groups.yahoo.com/api"
    LOGIN_URI="http://login.yahoo.com/"

in yahoogroupsapi.py
