### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by krandis** [IgnoredAmbience/yahoo-group-archiver#2]
I'm trying to run and each time it asks for password, after entering password, I get login failed.  I know I have typed in the correct password for the yahoo group.  I would appreciate help.

Thanks

**Comment by IgnoredAmbience** [comment]
I believe that the `cookie_t` and `cookie_y` parameters are now also required by Yahoo to login. I am not sure where these values are obtained, but they were noted as now required in #1. I have not used the tool since that PR was merged.

**Comment by krandis** [comment]
ok thanks

**Comment by logological** [comment]
I'm experiencing the same problem.  I'm not a Pythonista but am available to help test/troubleshoot.

**Comment by driph** [comment]
Archiving in light of the apocalypse, and experiencing the above issue as well.

**Comment by chaos986** [comment]
need to grab the T and Y values from your Yahoo login cookie.   
yahoo.py -u username -p password -ct t_cookie -cy y_cookie group

**Comment by rigr** [comment]
Please explain what part of the cookies needs to be given and in what form? The T value contains lots of characters with many "=" - do I need to set it all in "" or how do I set those? Thanks a lot!

**Comment by jmay** [comment]
I figured this out:

- visit Yahoo group in browser, log in with admin account
- inspect your cookies for groups.yahoo.com
- find the T and Y cookies
- take just the value part: a whole bunch of x=yyy parts separated by ampersands, but no whitespace
- put those in the -ct and -cy parameters on the command line for yahoo.py

It pulls the messages at a rate of about one per second, so will take a while if you have a large group.

**Comment by rigr** [comment]
Thanks, tried anything now and have no success.

yahoo.py -u username -p password -ct z=...&sk=asdasd...." 
-cy "v=1&n=asdasdasdasdd&l=asdasdasdasdasdasdasdasdasdasdas/o&p=020000000000000&r=nt&intl=de" Groupname
logging in...
Login failed

if -ct and -cy without "" I get an error "too few arguments, instruction "a" wrong or not found, instruction "sk" ...

What am I doing wrong?
Thank you!

**Edited to remove potential secrets**

**Comment by rigr** [comment]
Could I paste the values of T and Y in the code instead? where?

**Comment by jmay** [comment]
@rigr You are missing the quotes at the beginning of your -ct parameter.

In `yahoo.py`, scroll down to the line that includes `YahooGroupAPI` (close to the end) and replace the last two arguments with your values.

**Comment by rigr** [comment]
Thanks, Not yet there, :) I used "" to declare the variable, I'm however not sure if I should use that.

Error I receice is:

 File "C:\Users\richa\Downloads\yahoo-group-archiver-master_ignore amb\yahoo-group-archiver-master\yahoo.py", line 179
    yga = YahooGroupsAPI(args.group, "value of T containing multiple x=zzz", "value of Y containg v=aaa")
    ^
IndentationError: unexpected indent


??

**Comment by jmay** [comment]
That “unexpected indent” message is a python syntax alert.  Make sure your code lines up perfectly with the lines above & below. 4 spaces exactly.

**Comment by rigr** [comment]
Thanks Jason,

ok, corrected that, now it connetcts, but still 
logging in...
Login failed

I'm not the owner of the group, but can access it in the browser. I want to save all the messages but fear the hassles to do it by hand.

**Comment by jmay** [comment]
Check your username and password.

I needed to put @yahoo.com after my username to get it to work.

**Comment by rigr** [comment]
Tried username, tried email address, tried "" around the cookies, tried ' ' around them. :(

**Comment by chaos986** [comment]
yahoo.py -u username -p password -ct "z=..." -cy "v=1&n=..." -f -i -d lscaa

it must be the entire value of each T & Y cookie.  in "" no spaces inside the "" 

the groups I'm trying to save have too much spam to archive the messages, but the files and photos are what I am saving from old school clubs. 

I logged into groups fresh an then grabbed the values right after login. 

**Admin note:** Edited to remove cookie contents, please don't post full details, it's potentially allowing other people to access your account.

**Comment by rigr** [comment]
After poking around in the sources I finally had success by removing "s" from "https" in lines 9 and 10 of yahoogroupsapi.py  - now downloading 2500 messages and LOTS of files.
Thanks and best regards!
Richard

**Comment by rigr** [comment]
ok, http (without s) worked for messages and attachments but not for the rest. Will poke around some more (but downloaded most by hand before..)
received an error stating:
Exception raised on uri: http://groups.yahoo.com/api/v2/groups/RolandSamplers/files
{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[{"name":"READ"}]},{"resourceType":"CALENDAR","capabilities":[{"name":"READ"}]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"ygError":{"hostname":"gapi7.grp.bf1.yahoo.com","httpStatus":307,"errorMessage":"User does not have READ permission for FILE. Messa...","errorCode":1101,"sid":"SID:YHOO:groups.yahoo.com:5091fe4ef20250c803a668f9f8234671:0"}}

So there all likely is permissions problem.


Richard (sorry for flooding this, but maybe it helps someone)

**Comment by qurgh** [comment]
I know no Python, but after some googling and reading some docs, I added

`self.s.verify = False`

after 

`self.s.headers = {'Referer': self.BASE_URI}`

in yahoogroups.py __init__ to bypass SSL verification and it seems to be working. It gives me an InsecureRequestWarning with every call, but I don't really care since I'm only doing this for a few groups.

**Comment by rigr** [comment]
I just realized that I have a login problem - the group allows open access to the messages but files etc are restricted. So I am able to use some fantasy username and password and I can download the messages but NOT the files. Tried username and password with/out quotes, no difference.

**Comment by kgoroway** [comment]
Just in case someone else bumps into this.

In google chrome there are two different ways to see your cookies. 

1) Next to the URL in the top bar you can click on the icon just before the url to view cookies for the site you are on.  You will find both of the Y and T cookies in there, but they are displayed in a way that might deceive you.  You are only seeing the end of the cookie.  Make sure you scroll all the way to the left before copying the entire value.

2) go to Settings/Advanced/Privacy and Security/Site Settings/Cookies and Site Data/See all cookies and site data

search cookies for yahoo, and find yahoo.com

Your Y and T cookies are found there.  Copy the entire "contents".

**Comment by cmilanf** [comment]
Did everything regarding cookies and parameters, but it looks like it only works when I change the HTTPS endpoint by HTTP... This doesn't look like a good idea at all. Why could this be happening?

Tried bypassing TLS verification with `self.s.verify = False`, but didn't work with the authn issue.

**Comment by dossy** [comment]
@IgnoredAmbience curious why you reopened this?  Pretty sure this issue was due to the lack of the `T` and `Y` cookies, so updating the docs should resolve this?

**Comment by IgnoredAmbience** [comment]
Reopened this as I hadn't read the entire thread yet, only accepted the PR.

**Comment by IgnoredAmbience** [comment]
Combination of authentication issues and https verification issues. Second covered by #15.
