### ISSUE TITLE
Need canonical upstream repo

### ISSUE THREAD

**Issue by d235j** [IgnoredAmbience/yahoo-group-archiver#20]
Right now there are several divergent forks. This isn't the best for coordinating development.

A number of people in the #yahoosucks channel on EFnet IRC are working on this. Additionally there is a repo under @ArchiveTeam that will be used.

What should we use as the best / canonical upstream?

**Comment by IgnoredAmbience** [comment]
I'm happy for @archiveteam to be the canonical repository for this project,
I've not really got the time to support this project.

**Comment by IgnoredAmbience** [comment]
Slight change of mind, I plan to attempt a merge of the @archiveteam repo tomorrow (#21), and to then check the relevance of other PRs open against this repo, and content of other forks.

Likely to keep an option in for eml output mode, even if this does complicate the code.

Will stay on IRC to monitor archiveteam plans. Still happy for @archiveteam repo to become canonical (unsure best way to achieve this).

**Comment by IgnoredAmbience** [comment]
ArchiveTeam repo has now been merged in here, now working through bug reports on this repo.

**Comment by dossy** [comment]
Kinda disappointed that you merged in the removal of mbox-file style files (which can easily be turned into a maildir layout) in favor of ArchiveTeam's JSON change.

There's plenty of off-the-shelf tools for handling mbox/maildir (threaded viewers, email clients, etc.) ...

This is why open source is great: we can all have our own forks :)

**Comment by d235j** [comment]
@dossy we were running into encoding issues and at the moment, due to the shutdown timeline, accurate archival is higher priority than convenient viewing.

The plan is to add a separate json to mbox script. We'll definitely accept a PR giving us this!

**Comment by IgnoredAmbience** [comment]
As noted, intending to readd it as subsequent pass. Tbh, I should have reviewed some of the code pulled in from archive team more carefully, as it's making life harder in some places, rather than easier.

**Comment by IgnoredAmbience** [comment]
@dossy Is it ok if I integrate your changes into this repo?

**Comment by dossy** [comment]
@IgnoredAmbience I don't know how much work it'll be to integrate now that you merged in the ArchiveTeam changes, but if you have the time and inclination to do that work, go for it!
