### ISSUE TITLE
Enhancement: Cookie files

### ISSUE THREAD

**Issue by n4mwd** [IgnoredAmbience/yahoo-group-archiver#34]
The script gets everything except the membership list.  That's the most important part.  Any chance it could be modified to do that as well?

Also, my Y and T cookies are rather large for the command line.  Any chance they could be put inside files like "ycookie.txt" and "tcookie.txt".  Just raw cookie dough in the file terminated by a newline, linefeed, or EOF.

**Comment by IgnoredAmbience** [comment]
Accessing the membership list usually requires admin permissions for the group, when #29 is implemented the tool should be able to tell whether this is possible with the available permissions.

**Comment by IgnoredAmbience** [comment]
Agreed that a cookie file option would be useful.

**Comment by d235j** [comment]
@IgnoredAmbience scraping the membership list was added in https://github.com/IgnoredAmbience/yahoo-group-archiver/commit/16f63386890cfc1a37554efb575325c066eb01ec.

I believe if you're using admin cookies, you'll get emails, but even if you just have regular access you'll usually get useful data. Not all groups allow members access to the membership list, but most appear to.

**Comment by n4mwd** [comment]
What is the expected format of the cookie file?

**Comment by IgnoredAmbience** [comment]
I'm using whatever format that [LWPCookieJar](https://docs.python.org/2.7/library/cookielib.html?highlight=cookielib#cookielib.LWPCookieJar) takes, however using `--cookie-file` with all the relevant cookie parameters on the command line once will populate the file for you to use alone subsequently.

**Comment by n4mwd** [comment]
That wasn't clear before.  However, it works very well now that I know how to use it.  Maybe a readme enhancement is in order.
