### ISSUE TITLE
Only 20 photos per album are being downloaded

### ISSUE THREAD

**Issue by n4mwd** [IgnoredAmbience/yahoo-group-archiver#36]
I was able to get the photos to download, but then I noticed that it only downloaded 20 max photos from each album.  It correctly states the correct number of photos per album, but stops at 20.

I think it has already been mentioned as an enhancement, but it would be nice to have it skip the files that have already been downloaded.

**Comment by IgnoredAmbience** [comment]
I'm aware of this unfortunate bug, plan is to resolve it tomorrow. (references #22)

**Comment by n4mwd** [comment]
File download seems to stop after the 11th directory.

**Comment by n4mwd** [comment]
Any chance you could sanitize the filenames somehow and get rid of  illegal windows filename characters such as "/\*?" and just change them to '-' ?  I tried to go through and manually edit them on yahoo, but its easy for one to slip through and gum up the works.

**Comment by tripleee** [comment]
There are several related tickets about invalid file names, most of them probably mojibake rather than specifically illegal for Windows. See also e.g. #9

**Comment by IgnoredAmbience** [comment]
Fixed with 1d8a4b48
