### ISSUE TITLE
InsecureRequestWarning on Py2.7

### ISSUE THREAD

**Issue by bobblanchett** [IgnoredAmbience/yahoo-group-archiver#37]
InsecureRequestWarning,
2019-10-24 00:35:35 AEDT 335 INFO:archive_photos Fetching photo 'Taranto' (9/14)
/home/bob/.local/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

running ubuntu 18.04.3 LTS

**Comment by IgnoredAmbience** [comment]
Certificate verification was disabled as a temporary response to #15 and #24, where verification was occasionally failing for unknown reasons.

**Comment by bobblanchett** [comment]
cheers

**Comment by d235j** [comment]
Working on a better solution — we believe that Yahoo is sometimes malforming the certificate chain. Fix will probably involve including the correct certificate chain with the archiver.

**Comment by IgnoredAmbience** [comment]
Fixed by #44
