### ISSUE TITLE
refactor out code to more specific archive_* functions

### ISSUE THREAD

**Issue by IgnoredAmbience** [IgnoredAmbience/yahoo-group-archiver#40]
Currently we have lots of `archive_things` which have mixed focuses. Refactor these into chains of simpler `archive_thing(id)` functions.

We then also get an easier path to selective archival, for ad-hoc testing from the command line or resumption(?) for free.

**Comment by dossy** [comment]
Honestly, since Y! Groups is going away, there's no real reason to create more abstractions - ultimately in a few months, this code will be obsolete and no longer usable, anyway.

**Comment by IgnoredAmbience** [comment]
Will do it as and when needed for feature support.
