### ISSUE TITLE
RFE: Idiot-proof way to specify email start or stop number

### ISSUE THREAD

**Issue by ugcheleuce** [IgnoredAmbience/yahoo-group-archiver#42]
Request for enhancement:

It would be nice if you can add an idiot-proof way to specify from which message to start downloading, and optionally also specify up to which message should be downloaded.  [I don't know Python and my tinkering with yahoo.py was unsuccessful.]  This would allow one to continue after a while, or to download only certain messages (if there are too many).

One implementation may be to allow users to specify "startatmail" and "stopatmail" variables near the top of yahoo.py.

**Comment by dossy** [comment]
@ugcheleuce check my `dossy` branch in my [dossy/yahoo-group-archiver](https://github.com/dossy/yahoo-group-archiver/tree/dossy) fork, where I've introduced `--start` and `--stop` for email archiving that lets you specify a starting and ending message ID to extract.

**Comment by n4mwd** [comment]
This would be a good feature for photos and files as well.  Sometimes the download stops due to an crash or user intervention and it would be great to be able to restart where it was left off.

**Comment by ugcheleuce** [comment]
> https://github.com/IgnoredAmbience/yahoo-group-archiver/issues/42#issuecomment-545923269
> @ugcheleuce check my `dossy` branch in my [dossy/yahoo-group-archiver](https://github.com/dossy/yahoo-group-archiver/tree/dossy) fork, where I've introduced `--start` and `--stop` for email archiving that lets you specify a starting and ending message ID to extract.

Thanks for your reply, @dossy.  I could not get the dossy version to work (got an unindent related error), but I'll check both projects again closer to the deadline.
