### ISSUE TITLE
Retry option 

### ISSUE THREAD

**Issue by Pablo2m** [IgnoredAmbience/yahoo-group-archiver#52]
Hello, I have some intermittences in the electricity supply and when the download of the messages is interrupted by a power outage (yes, I should buy a UPS) when I try again it starts to go down again from the end. Could you add an option to download only the missing messages?

**Comment by ugcheleuce** [comment]
In the mean time, see the reply to my post here:
https://github.com/IgnoredAmbience/yahoo-group-archiver/issues/42

**Comment by IgnoredAmbience** [comment]
As noted will do this with #42
