### ISSUE TITLE
An offset for the downloaded data would be nice

### ISSUE THREAD

**Issue by jmeile** [IgnoredAmbience/yahoo-group-archiver#57]
I saw this in another yahoo archiver: if you interrupt the transfer, then next time that you run the script it will continue where you were the last time. This could be easily implemented with a log file where you save the last processed file, ie: a message, an attachment, etc. Then next time you can just go directly were the transfer was interrupted. Since yahoo stores everything in order of creation, this wouldn't be any problem. Just a count variable. My two cents.

**Comment by IgnoredAmbience** [comment]
Will handle this with #42
