### ISSUE TITLE
Crashes on non-alphanumeric folder name for files

### ISSUE THREAD

**Issue by andrewferguson** [IgnoredAmbience/yahoo-group-archiver#71]
Some groups store files in non-alphanumeric folder names, and this currently causes the script to crash.
<pre>2019-10-26 11:24:33.172 BST INFO archive_files Fetching directory '∮∮♀♂表格收集＄＄∮♂♁★★' (1/15)
Traceback (most recent call last):
  File "./yahoo.py", line 696, in <module>
    archive_files(yga)
  File "./yahoo.py", line 219, in archive_files
    with Mkchdir(name):
  File "./yahoo.py", line 568, in __enter__
    os.chdir(self.d)
OSError: [Errno 2] No such file or directory: ''</pre>

This is on the [wizaschool group](https://hk.groups.yahoo.com/neo/groups/wizaschool/info).

**Comment by andrewferguson** [comment]
Here's the `fileinfo.json` for the group. (With .txt added to the end so GitHub is happy).
[fileinfo.json.txt](https://github.com/IgnoredAmbience/yahoo-group-archiver/files/3774725/fileinfo.json.txt)

**Comment by IgnoredAmbience** [comment]
files api doesn't give unique ids to uploaded folders or files, consider use of prefixed created time, or hash of non-printable name

**Comment by IgnoredAmbience** [comment]
Further notes, directory names need to be reproducible just from the name string, as we don't have metadata on further traversal into the directory. Seems like appending a hash will be the best route.
