### ISSUE TITLE
Don't trust yahoo "GetMyData"

### ISSUE THREAD

**Issue by n4mwd** [IgnoredAmbience/yahoo-group-archiver#87]
This is not really a bug with this program, but a bug with yahoo's GetMyData service.  In addition to using this script to get all my data, I also used the yahoo GetMyData feature.  What they sent was woefully incomplete.  Meanwhile, this script by IgnoredAmbience got everything.  One of my groups had almost 70K messages and this script got them all.

So this is just an FYI.  If you were depending on using the yahoo GetMyData service to archive your groups, you will be disappointed.

**Comment by IgnoredAmbience** [comment]
Thanks for the detail, I hope you don't mind me quoting this ticket in the readme.

**Comment by n4mwd** [comment]
No problem quoting me.  The yahoo tool seems to only return photos that I actually posted.
I'm working on a compliment tool to read your json files and convert them into emls and a single XML file suitable for importing into phpbb or others.

**Comment by Kuipo** [comment]
I would like to +1 this.

I am part of a yahoo group that goes back to November of 1998 well before it was even known as Yahoo Groups.  The package that Yahoo sent me doesn't have a majority of the data and the first post Yahoo gave me is from Nov of 2000.

Using the script gives me all the data, files, attachments, etc.  It's much better.

**Comment by dominiquejavet** [comment]
After a couple of test, it seems that the Yahoo getMyData tool provide only your contribution to the group, but doesnt give you the whole group data. Really not a valid solution to backup your messages.
