### ISSUE TITLE
UnicodeDecodeError in logging

### ISSUE THREAD

**Issue by rigr** [IgnoredAmbience/yahoo-group-archiver#88]
Hi thanks for all your work and efforts!

I was able to download all required data but see many erropts while archiving:

Here the error I received:

> Traceback (most recent call last):
>   File "C:\Python27\lib\logging\__init__.py", line 868, in emit
>     msg = self.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 741, in format
>     return fmt.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 476, in format
>     raise e
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 35: ordinal not in range(128)
> Logged from file connectionpool.py, line 959
> Traceback (most recent call last):
>   File "C:\Python27\lib\logging\__init__.py", line 868, in emit
>     msg = self.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 741, in format
>     return fmt.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 476, in format
>     raise e
> 
> ...
> 
> Logged from file yahoogroupsapi.py, line 109
> Traceback (most recent call last):
>   File "C:\Python27\lib\logging\__init__.py", line 868, in emit
>     msg = self.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 741, in format
>     return fmt.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 476, in format
>     raise e

... and so on.

Best regards
Richard

**Comment by Pablo2m** [comment]
Try using python 3

**Comment by IgnoredAmbience** [comment]
Thanks for the report, I'm going to need to look at all the logging code more closely.

**Comment by SanneSideUp** [comment]
> Try using python 3

Not a good recommendation. I did that (python 3.8) now the script doesn't work anymore at all! Throws the following error:

> File "C:\YahooGroups-Archiver\yahoo.py", line 3, in <module>
>     import yahoogroupsapi
>   File "C:\YahooGroups-Archiver\yahoogroupsapi.py", line 17, in <module>
>     import requests  # Must be imported after capture_http
> ModuleNotFoundError: No module named 'requests'

**Comment by Pablo2m** [comment]
Hello, Python 2 and python 3 behave like isolated environments, you must install requests again:
pip install requests
After that I should run, if you still have a problem answer this message, I have 20 GB of information downloaded using python 3

**Comment by IgnoredAmbience** [comment]
I think this issue should now be fixed in master, please reopen if not.
