### ISSUE TITLE
Yahoo "Get My Data" tool

### ISSUE THREAD

**Issue by danb35** [IgnoredAmbience/yahoo-group-archiver#94]
The README mentions this tool, and I've now used it--here's what it seems to do.  It provides a single .zip file containing all messages (in .mbox format), files, and links for all groups of which you're a member.  The messages include full email addresses.  Photos do not appear to be included.  You use that tool to make a request, and once they get it ready (which took about a week for me), they send you a link where you can download the file.

**Comment by IgnoredAmbience** [comment]
Thanks for the detail, added to the readme.

**Comment by leafhy** [comment]
The response I got from "Get My Data" was "Your download request has been completed, but no data of this type is available in your account." Thankyou for creating a tool that works.
