### ISSUE TITLE
README.md usage instructions need a few tweaks

### ISSUE THREAD

**Issue by sberl** [IgnoredAmbience/yahoo-group-archiver#95]
I just installed on my MacOS system. In the "usage" section it says to use the command "pip install -r requirements.txt", but on my system this did not work. 
I needed to use the command "sudo pip install -r requirements.txt".

Also the instructions for getting the cookie values in Chrome say to use the "circled letter i", but on my browser window I needed to click the little padlock icon in front of the URL instead.

**Comment by IgnoredAmbience** [comment]
I need to have a think about improving these instructions in general, they're certainly aimed at people familiar with python at present, which isn't a good situation for accessibility. Though, I'm unwilling to suggest people use the system install path for these packages, and the `--user` install path seems to break on some people's systems.

Thanks for the suggestion to use the padlock, I think it depends whether you go to the http or https version of the website, added both to the readme.

**Comment by IgnoredAmbience** [comment]
Will track the packaging issue on #97.
