### ISSUE TITLE
How to resume process after it stalled halfway

### ISSUE THREAD

**Issue by Sadi58** [IgnoredAmbience/yahoo-group-archiver#98]
Thanks to this script I've begun archiving my Yahoo group, but it stalled at some point (while downloading message (and or attachment) 32757 of 45312.
As it already took some hours to come to that point, I'd like to resume from there hopefully completing messages and then moving on to photos, etc.
Is this possible at all?

**Comment by IgnoredAmbience** [comment]
To fetch a subset of emails, you can add the options `--email --start messageid` replacing `messageid` with the message id of where it got to.

To fetch only the other types of content, explicitly specify the types required on the command line, eg: `-at -f -i -p` will get attachments, files, images, polls. The full list of options can be seen with `--help`.
