### ISSUE TITLE
Instructions unclear on how cookiefile should be formatted

### ISSUE THREAD

**Issue by Kuipo** [IgnoredAmbience/yahoo-group-archiver#99]
I am trying to make use of the --cookiefile argument but am not clear about how to format the file.  I have created the file by hand, but haven't gotten it correct sadly.  The readme doesn't explain how I should format the file.  I get the following errors:
```
2019-11-05 12:36:52.972 PST ERROR archive_email Couldn't access Messages functionality for this group
2019-11-05 12:36:53.259 PST ERROR archive_files Couldn't access Files functionality for this group
etc.
```
The current format I'm using is (with values removed and replaced by ...):
```
#LWP-Cookies-2.0
Set-Cookie3: T="..."; path="/"; domain=".yahoo.com"; path_spec; expires="2020-10-29 12:16:35Z"; version=0
Set-Cookie3: Y="..."; path="/"; domain=".yahoo.com"; path_spec; expires="2020-10-29 12:16:35Z"; version=0
```

**Comment by IgnoredAmbience** [comment]
You can use the `-ct`, `-cy` and `-ce` parameters with `--cookiefile` and it will save the cookies to the given file for you. You can then use just the `--cookiefile` parameter on the next run.

**Comment by Kuipo** [comment]
Cheers.  That worked for me.  I tried to look for something like that but must have missed it.
